"""Generates user guide for finding financial metrics"""

from pathlib import Path


class GuideGenerator:
    """Creates documentation for users"""

    def generate(self, output_path: str | Path = "output/guide.md") -> None:
        """Generate the user guide

        Creates a markdown file explaining how to find the 5 key metrics
        using Yahoo Finance or other sources.
        """
        guide_content = """# Stock Analysis User Guide

## How to Find Key Financial Metrics

This guide explains how to find the 5 key financial metrics used in our stock analysis.

---

## 1. Profit Margin

**Formula:** Net Income / Total Revenue

**How to find on Yahoo Finance:**
1. Go to finance.yahoo.com and search for a company ticker
2. Click on the "Financials" tab
3. Look at the Income Statement
4. Find "Net Income" (most recent period)
5. Find "Total Revenue"
6. Divide Net Income by Total Revenue

**What it means:** Profit margin shows what percentage of revenue remains as profit after all expenses.

---

## 2. Operating Margin

**Formula:** Operating Income / Total Revenue

**How to find on Yahoo Finance:**
1. On the same Income Statement
2. Find "Operating Income" or "Operating Income Total"
3. Divide by Total Revenue

**What it means:** Operating margin indicates profitability from core business operations.

---

## 3. Free Cash Flow

**Definition:** Cash generated by operations minus capital expenditures

**How to find on Yahoo Finance:**
1. Click on the "Financials" tab
2. Scroll to the Cash Flow Statement
3. Look for "Free Cash Flow" (may be labeled as "Cash Flow From Operations Total"minus capital expenditures)

**Alternative:** Sometimes shown directly as "Free Cash Flow"

**What it means:** FCF represents cash available for dividends, debt repayment, or reinvestment.

---

## 4. Return on Invested Capital (ROIC)

**Formula:** NOPAT / Invested Capital
- NOPAT = Operating Income × (1 - tax rate)
- Invested Capital = Total Assets - Cash

**How to find on Yahoo Finance:**
1. **Operating Income:** Income Statement
2. **Tax Rate:** Look for "Effective Tax Rate" in key statistics or calculate from income taxes
3. **Total Assets:** Balance Sheet
4. **Cash:** Balance Sheet (Cash and Cash Equivalents) or quote page

**Steps:**
- Calculate NOPAT = Operating Income × (1 - tax rate)
- Calculate Invested Capital = Total Assets - Cash
- ROIC = NOPAT / Invested Capital

**What it means:** ROIC measures how efficiently a company generates returns from invested capital.

---

## 5. Interest Coverage Ratio

**Formula:** EBIT / Interest Expense

**How to find on Yahoo Finance:**
1. **EBIT:** Income Statement (Earnings Before Interest and Taxes)
2. **Interest Expense:** Income Statement (Interest Expense, often shown as negative)

**Steps:**
- Find EBIT (may be listed as "Operating Income" or "EBIT")
- Find "Interest Expense" (usually a negative number)
- Divide EBIT by absolute value of Interest Expense

**What it means:** This ratio indicates how easily a company can pay interest on its debt. Higher is better.

---

## Tips for Manual Analysis

- Always use the most recent annual or quarterly data
- Be consistent with time periods (all annual or all quarterly)
- Compare companies within the same industry
- Watch for negative values (e.g., negative earnings) which can distort ratios
- Use multiple periods to spot trends

---

## Data Sources

Primary: Yahoo Finance (free)
Alternative: SEC EDGAR filings, Morningstar, or brokerage platforms

---

*Generated by Stock Agent and Guide*
"""

        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(guide_content)
